db:
    username: ${username.value:postrges}
    password: pass
    driver: PostgesDriver
    url: postgres:5432
    hosts: localhost,127.0.0.1
    properties:
        first : 123
        second : 567
        third.value : Third
    pool:
        size:12
        timeout:10
    pools:
        - size: 1
          timeout: 1
        - size: 2
          timeout: 2
        - size: 3
          timeout: 3
spring:
    profiles:
        active: qa

logging:
    level:
        root: WARN
        com.dmved.spring.database.pool: INFO
    file:
        name: application.log
        path: /

