db:
    username: ${username.value:postrges}
    password: pass
    driver: PostgesDriver
    url: postgres:5432
    hosts: localhost,127.0.0.1
    pool:
        size:12
        timeout:10
    pools:
        - size: 1
          timout: 1
        - size: 2
          timeout: 2
        - size: 3
          timeout: 3
